wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.10
    start_time: 1666920215.980492
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.10
      5: 0.13.4
      8:
      - 1
      - 5
criterion:
  desc: null
  value: CrossEntropyLoss()
dataset:
  desc: null
  value: power_and_entropy
epochs:
  desc: null
  value: 1000
learning_rate:
  desc: null
  value: 0.001
loops_config:
  desc: null
  value: true
model:
  desc: null
  value:
    activation: ReLU
    hidden_channels: 128
    num_graph_conv_blocks: 4
    readout: global_mean_pool
node_representation_size:
  desc: null
  value: 8
training_batch_size:
  desc: null
  value: 50
validation_batch_size:
  desc: null
  value: 50
weight_config:
  desc: null
  value: unweighted_static_threshold
weight_decay:
  desc: null
  value: 0.001
